config/routes.rb
Techart::Application.routes.draw do
 
  

   
  resources :articles do
    collection do
      
    end
  end
  
  resources :users do
    collection do
      get :login
    end
  end

    root :to => "articles#index"

    match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :views
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :views
  has_many :comments
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #before_filter :authorize
  

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
   def view
    @article = Article.all
    end
  
  def create
    @user = User.find_by_user_name(session[:user_id])
    @article = Article.new do |a|
      a.art_title = params[:article][:art_title]
      a.description = params[:article][:description]
      a.user_id = @user.id
    end
    respond_to do |format|
      if @article.save
         format.html {redirect_to("/", :notice => 'Article created successfully')}
         format.xml {render :xml => @article, :status => :created, :location => @article }
      else
         format.html {render :action => "new"}
         format.xml {render :xml => @article.errors, :status => :unprocessable_entry }
      end
    end
  end

  def new
    @article = Article.new
        
  end

  def show
    if session[:user_id]
      @article = Article.where(:id => params[:id]).first
      @article.count = @article.count + 1
      @article.save 
      respond_to do |format|
        format.html # view.html.erb
        format.xml  { render :xml => @article }
      end
    else
        check
    end
  end

  def delete_article
    
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to :controller => 'articles', :action => 'index'
    
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def index
    @article1 = Article.order(:'created_at desc')
      @article2 = Article.order(:'count desc')
    #find(:all, :order => "updated_at")    
  end
  
  def search
    aa
  end

  def link_check
      if session[:user_id]== Article.user_id
        equal
      else
        notequal
      end
  end
  
  def check
    if User.find_by_id(session[:user_id])
      
    else
      redirect_to login_users_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml=> @user}
    end
  end
  
  def users
  end
  
  def login
  end
  
  def logout
    reset_session
    redirect_to "/"
  end
  
  def verify
    @user = User.new(params[:user])
    if User.find_by_user_name_and_password(@user.user_name, @user.password)
      session[:user_id] = @user.user_name
      #id[:user_id] =@user.id
      redirect_to("/articles")# ,:notice => 'login successfull welcome ' + session[:user_id] )
    else
      flash[:notice] = "invalid username/password"
      redirect_to "/users/login"
    end
  end
  
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html {redirect_to(@user, :notice => 'User created successfully')} # redirect to main page....
        format.xml {render :xml => @user, :status => :created, :location => @user}
      else
        format.html {render :action => "new"}
        format.xml {render :xml => @user.errors, :status => :unprocessable_entry }
      end
    end
  end
  
  def edit
    @user = User.find(params[:user_id])
  end
  
  def delete
  end
  
  def update
  end
  
  def show
    @user1 = User.where(:id => params[:id]).first
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def article_list(user)
    
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<% if @article.errors.any? %>
		<div id="error exp">
		    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this product from being saved:</h2>
		    <ul>
		        <% @article.errors.full_messages.each do |msg| %>
		        <li>
		            <%= msg %>
		        </li>
		        <% end %>
		    </ul>
		</div>
	<% end %>
	<div class="field">
	    <%= f.label :Title %>
	    <br/>
	    <%= f.text_field :art_title %>
	</div>
	<div class="field">
	    <%= f.label :Description %>
	    <br/>
	    <%= f.text_area :description %>
		<br />
		<%= f.submit%>
	</div>
<% end %>

app/views/articles/create.html.erb
<h1>Article#create</h1>
<p>Find me in app/views/article/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Article#delete</h1>
<p>Find me in app/views/article/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1>Article#edit</h1>
<p>Find me in app/views/article/edit.html.erb</p>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<table cellspacing="10">
	<tr>
		<td> <b>Latest Articles</b> </td>
		<td> <b>Popular Articles</b> </td>
	</tr>
	<tr>
		<td>
			<% @article1.each do |article| %>
				<dl>
					<dt><%=link_to article.art_title, article %></dt>
					<dd><%=truncate(strip_tags(article.description),:length => 40)%></dd>
					<br/>
				</dl>
			<%end%>
		</td>
		<td>
			<% @article2.each do |article| %>
				<dl>
					<dt><%=link_to article.art_title, article %></dt>
					<dd><%=truncate(strip_tags(article.description),:length => 40)%></dd>
					<br/>
				</dl>
			<%end%>
		</td>
	</tr>
</table>

app/views/articles/new.html.erb
<%= render :partial => 'form' %>

app/views/articles/search.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Untitled Document</title>
	</head>
	<body>
		<h1>You are in Search page</h1>
		<h2>Page Under Construction</h2>
			
	</body>
</html>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.art_title %>
</p>
	 By <%=link_to @article.user.user_name,@article.user%>

<p>
  <b>Description:</b>
  <%= @article.description %>
  
</p>
<%= render :partial => 'renders/comment_form' %>

<% if @article.user.user_name == session[:user_id]%>
	<%= link_to 'Edit', edit_article_path(@article) %>
	<%= link_to 'Destroy', :controller => 'articles', :action => 'delete_article', :id => @article %>
	<%= link_to 'Back',:back %>
<%else%>
	<%= link_to 'Back', :back %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Techart Blog</title>
        <%= stylesheet_link_tag "techartstyle", :media => "all" %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
    </head>
    <body>
	    
    <div>
        <%= yield %>
    </div>
	
</div>
</body>
</html>

app/views/layouts/articles.html.erb
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<%= stylesheet_link_tag "techartstyle", :media => "all" %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
	</head>
	<body style="margin: 0px;" id="body-style">
		<%= render :partial => 'renders/header' %>
		<div id="left-side">
			<%= render :partial => 'renders/side' %>
		</div>
    	<div>
        	<%= yield %>
    	</div>
	
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<%= stylesheet_link_tag "techartstyle", :media => "all" %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
	</head>
	<body style="margin: 0px;" id="body-style">
	<%= render :partial => 'renders/header' %>
	<div>
        <%= yield %>
    </div>
	
</div>
</body>
</html>

app/views/renders/_comment_form.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Comments</title>
	</head>
	<body>
		<table>
		<%form_tag %>
			<tr>
				<td> Email-ID : </td>
				<td> <input id="" email_id="" type="text" /> </td>
				
			</tr>
			<tr>
				<td> Name : </td>
				<td> <input id="" email_id="" type="text" /></td>
				
			</tr>
			<tr>
				<td> Comment : </td>
				<td><input id="" email_id="" type="label" /> </td>
				
			</tr>
		</table>
		<%= submit_tag "Feedback" %>
	</body>
</html>

app/views/renders/_header.html.erb
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <title>TECH-ART</title>
        <%= stylesheet_link_tag "techartstyle", :media => "all" %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
		<script type="text/javascript">
					var c=Date();
					var t;
					var timer_is_on=0;
					
					function timedCount()
					{
					document.getElementById('txt').value=c;
					c=Date();
					t=setTimeout("timedCount()",1000);
					}
					
					function doTimer()
					{
					if (!timer_is_on)
					  {
					  timer_is_on=1;
					  timedCount();
					  }
					}
			</script> 
    </head>
    <body onload="doTimer()">
    	<div id="banner">
            <%= image_tag("globe.gif",:size=> "100x100") %>
            <%= @page_title ||"Welcome to TechArt Blog" %>
            <form action="articles/search" method="get">
                <input id="q" name="q" type="text" /><input name="commit" type="submit" value="Search" />
            
				
			
			</form>
			
        </div>
		<input type="text" id="txt" style="background:transparent;border:none; float: right;color:maroon" disabled=true />
		
    </body>
</html>

app/views/renders/_side.html.erb
<div>
	<% if session[:user_id] %>
	    <%= "Welcome "+ session[:user_id] %>
	    <%=button_to "logout",{:action=>'logout', :controller=>'users'},{:id => "button-color"} %>
		<% @user = User.find_by_user_name(session[:user_id])%>
		<% @article = Article.find_by_user_id(@user.id)%>
		<%=button_to "New Article     ",new_article_path, {:id => "button-color"}%>
	
		<%= button_to "Delete Article", {:controller => "articles", :action => "delete_article"}, {:id => "button-color"} %>
		<%=button_to "Edit profile      ",{:action => "edit"},{:id => "button-color"} %>
		<%=button_to "Delete profile",{:action => "delete"},{:id => "button-color"}%>
	
		<%="Articles created by " + @user.user_name%>
		<br />
		<% for article in @user.articles %>
			=>> <%=link_to article.art_title,article %><br />
		<% end %>
		<%#=link_to @article.art_title, @article %>
	  <% else %>
	    <%= button_to 'Login', login_users_path, {:id => "button-color"}%>
	    <%= button_to 'New Registration', new_user_path ,{:id => "button-color"}%>
	  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<h2><%= pluralize(@user.error.count,"error") %>prohibited this product from being saved:</h2>
<ul>
    <%@user.error.full_message.each do |msg| %>
    <li>
        <%= msg %>
    </li>
</ul>
<% end %>
<%end %>
<table>
	<tr>
		<td>	<%= f.label :FirstName %> </td>
		<td>	<%=f.text_field :fname %> </td>
		<td>	<%= f.label :LastName %> </td>
		<td>	<%=f.text_field :lname %> </td>
	</tr>
	
	<tr>
	<td>		<%= f.label :Username %> </td>
	<td>		<%= f.text_field :user_name %> </td>
	</tr>
	
	<tr>	
		<td>	<%=f.label :Password %> </td>
		<td>	<%= f.password_field :password %> </td>
		<td>	<%= f.label :Retypepassword %> </td>
		<td>	<%= f.password_field :password %> </td>
	</tr>
	<tr>
		<td>	<%= f.label :Age %> </td>
		<td>	<%= f.text_field :age %> </td>
	</tr>	
		<td>	<%= f.label :Address %> </td>
		<td>	<%= f.text_area :address %> </td>
		<td>	<%= f.submit%> </td>
	</tr>		
</table>
<%end %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div id="main">
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<h2><%= pluralize(@user.error.count,"error") %>prohibited this product from being saved:</h2>
<ul>
    <%@user.error.full_message.each do |msg| %>
    <li>
        <%= msg %>
    </li>
</ul>
<% end %>
<%end %>
<%= f.label :FirstName %>
<%=f.text_field :fname %>
<%= f.label :LastName %>
<%=f.text_field :lname %>
<br/>
<%=f.label :Password %>
<%= f.password_field :password %>
<%= f.label :Retypepassword %>
<%= f.password_field :password %>
<br/>
<%= f.label :Age %>
<%= f.text_field :age %>
<br/>
<%= f.label :Address %>
<%= f.text_area :address %>
<%= f.submit %>
<%end %>
</div>

app/views/users/login.html.erb
<div id='left-side'>
	<h1>Login</h1>
	<p> <%= flash[:notice] %></p>
	<h2>Please enter your details</h2>
	<%= form_for(:user,:url => {:controller => "users", :action => "verify"}) do |f| %>
		<table cellspacing="1"><tr>
			<td><%= f.label :"Name :" %></td>
			<td><%= f.text_field :user_name, :maxlength => "15" %></td></tr>
			<tr><td><%= f.label :"Password:"%></td>
			<td><%= f.password_field :password, :maxlength => "15" %></td></tr>
		<table cellspacing="30"><tr>
		<td><%= f.submit :Login, {:id => "button-color"}%></td>	
	<%end%>
		<td><%=button_to "Cancel", "/",  {:id => "button-color"}%></td>
		</tr>
		</table>
</div>

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/new.html.erb
<div id="left-side">
	<%=button_to "Back", '/',{:id => "button-color"}%>
</div>	
<div id="bck_img">
<h1>User Registration Form</h1>
<p>Please fill all the details</p>
<%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<div id ='left-side'>
	<%=render :partial => 'renders/side'%>
</div>
 
Name: <%= @user1.fname%> <%= @user1.lname%>

<p>Age : <%= @user1.age%></p>

<p>Address : <%= @user1.address%></p>

<%= link_to "Back", :back %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/users.html.erb
<h1>Users#users</h1>
<p>Find me in app/views/users/users.html.erb</p>

app/views/users/verify.html.erb
<h1>Users#verify</h1>
<p>Find me in app/views/users/verify.html.erb</p>